<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>GenerateTablebase</AssemblyName>
    <RootNamespace>GenerateTablebase</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CheckersEngine.csproj" />
  </ItemGroup>
</Project>
